; ModuleID = "PsyNeuLinkModule-4"
target triple = "unknown-unknown-unknown"
target datalayout = ""

define void @"_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__learning_3"({{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* noalias nonnull %".1", {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* noalias nonnull %".2", {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* noalias nonnull %".3", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* noalias nonnull %".4") argmemonly!dbg !6
{
entry:
  %"ptr_state_is_finished_flag_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 4 , !dbg !7
  %"ptr_state_is_finished_flag_WORKING MEMORY (fnn) Input_CIM_hist0" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 4, i32 0 , !dbg !7
  %"ptr_state_num_executions_before_finished_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 6 , !dbg !7
  %"ptr_state_num_executions_before_finished_WORKING MEMORY (fnn) Input_CIM_hist0" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 6, i32 0 , !dbg !7
  %"ptr_param_max_executions_before_finished_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".1", i32 0, i32 5 , !dbg !7
  %".6" = load double, double* %"ptr_state_is_finished_flag_WORKING MEMORY (fnn) Input_CIM_hist0", !dbg !7
  %".7" = fcmp oeq double %".6", 0x3ff0000000000000 , !dbg !7
  br i1 %".7", label %"entry.if", label %"entry.endif", !dbg !7
entry.if:
  store double              0x0, double* %"ptr_state_num_executions_before_finished_WORKING MEMORY (fnn) Input_CIM_hist0", !dbg !7
  br label %"entry.endif", !dbg !7
entry.endif:
  br label %"entry.endif_loop", !dbg !7
entry.endif_loop:
  %".12" = call i1 @"_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__learning_3_internal_4"({{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".1", {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".1"), !dbg !7
  %".13" = load double, double* %"ptr_state_num_executions_before_finished_WORKING MEMORY (fnn) Input_CIM_hist0", !dbg !7
  %".14" = fadd double %".13", 0x3ff0000000000000, !dbg !7
  store double %".14", double* %"ptr_state_num_executions_before_finished_WORKING MEMORY (fnn) Input_CIM_hist0", !dbg !7
  %".16" = load double, double* %"ptr_param_max_executions_before_finished_WORKING MEMORY (fnn) Input_CIM", !dbg !7
  %".17" = fcmp oge double %".14", %".16" , !dbg !7
  %"ptr_param_execute_until_finished_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".1", i32 0, i32 4 , !dbg !7
  %".18" = load double, double* %"ptr_param_execute_until_finished_WORKING MEMORY (fnn) Input_CIM", !dbg !7
  %".19" = fcmp oeq double %".18",              0x0 , !dbg !7
  %".20" = or i1 %".12", %".17", !dbg !7
  %".21" = or i1 %".20", %".19", !dbg !7
  br i1 %".21", label %"entry.endif_loop.if", label %"entry.endif_loop.endif", !dbg !7
entry.endif_end:
  ret void, !dbg !7
entry.endif_loop.if:
  %".23" = uitofp i1 %".20" to double , !dbg !7
  store double %".23", double* %"ptr_state_is_finished_flag_WORKING MEMORY (fnn) Input_CIM_hist0", !dbg !7
  br label %"entry.endif_end", !dbg !7
entry.endif_loop.endif:
  br label %"entry.endif_loop", !dbg !7
}

define i1 @"_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__learning_3_internal_4"({{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* nonnull %".1", {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* nonnull %".2", {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* nonnull %".3", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* nonnull %".4", {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* nonnull %".5") argmemonly!dbg !9
{
entry:
  %"input_ports_out" = alloca {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, !dbg !10
  %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".5", i32 0, i32 1 , !dbg !10
  %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 1 , !dbg !10
  %".7" = getelementptr {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}, {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", i32 0, i32 0 , !dbg !10
  %".8" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", i32 0, i32 0 , !dbg !10
  %".9" = getelementptr {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}* %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 0 , !dbg !10
  %".10" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 0 , !dbg !10
  call void @"_InputPort_INPUT_CIM_CURRENT_CONTEXT_InputPort_0__5"({{double, {}, double, {}}, {}, {}}* %".9", {{}}* %".10", [2 x [25 x double]]* %".7", [25 x double]* %".8"), !dbg !10
  %".12" = getelementptr {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}, {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", i32 0, i32 1 , !dbg !10
  %".13" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", i32 0, i32 1 , !dbg !10
  %".14" = getelementptr {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}* %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 1 , !dbg !10
  %".15" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 1 , !dbg !10
  call void @"_InputPort_INPUT_CIM_RETRIEVED_STIMULUS_InputPort_0__7"({{double, {}, double, {}}, {}, {}}* %".14", {{}}* %".15", [2 x [8 x double]]* %".12", [8 x double]* %".13"), !dbg !10
  %".17" = getelementptr {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}, {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", i32 0, i32 2 , !dbg !10
  %".18" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", i32 0, i32 2 , !dbg !10
  %".19" = getelementptr {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}* %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 2 , !dbg !10
  %".20" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 2 , !dbg !10
  call void @"_InputPort_INPUT_CIM_CURRENT_TASK_InputPort_0__9"({{double, {}, double, {}}, {}, {}}* %".19", {{}}* %".20", [2 x [2 x double]]* %".17", [2 x double]* %".18"), !dbg !10
  %".22" = getelementptr {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}, {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", i32 0, i32 3 , !dbg !10
  %".23" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", i32 0, i32 3 , !dbg !10
  %".24" = getelementptr {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}* %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 3 , !dbg !10
  %".25" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 3 , !dbg !10
  call void @"_InputPort_INPUT_CIM_CURRENT_STIMULUS_InputPort_0__11"({{double, {}, double, {}}, {}, {}}* %".24", {{}}* %".25", [2 x [8 x double]]* %".22", [8 x double]* %".23"), !dbg !10
  %".27" = getelementptr {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}, {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", i32 0, i32 4 , !dbg !10
  %".28" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", i32 0, i32 4 , !dbg !10
  %".29" = getelementptr {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}* %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 4 , !dbg !10
  %".30" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 4 , !dbg !10
  call void @"_InputPort_INPUT_CIM_RETRIEVED_CONTEXT_InputPort_0__13"({{double, {}, double, {}}, {}, {}}* %".29", {{}}* %".30", [2 x [25 x double]]* %".27", [25 x double]* %".28"), !dbg !10
  %".32" = getelementptr {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}, {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", i32 0, i32 5 , !dbg !10
  %".33" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", i32 0, i32 5 , !dbg !10
  %".34" = getelementptr {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}* %"ptr_param_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 5 , !dbg !10
  %".35" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_input_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 5 , !dbg !10
  call void @"_InputPort_INPUT_CIM_Target_InputPort_0__15"({{double, {}, double, {}}, {}, {}}* %".34", {{}}* %".35", [1 x [2 x double]]* %".32", [2 x double]* %".33"), !dbg !10
  %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 2 , !dbg !10
  %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM.1" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 2 , !dbg !10
  %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 2, i32 0 , !dbg !10
  %"ptr_param_function_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".5", i32 0, i32 3 , !dbg !10
  %"ptr_state_function_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 3 , !dbg !10
  call void @"_Identity_Identity_Function_0__learning_17"({}* %"ptr_param_function_WORKING MEMORY (fnn) Input_CIM", {}* %"ptr_state_function_WORKING MEMORY (fnn) Input_CIM", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"input_ports_out", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0"), !dbg !10
  %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 5 , !dbg !10
  %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM_hist0" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 5, i32 0 , !dbg !10
  %"num_executions_TimeScale.CONSIDERATION_SET_EXECUTION_ptr" = getelementptr [5 x i32], [5 x i32]* %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 0 , !dbg !10
  %".38" = load i32, i32* %"num_executions_TimeScale.CONSIDERATION_SET_EXECUTION_ptr", !dbg !10
  %".39" = add i32 %".38", 1, !dbg !10
  store i32 %".39", i32* %"num_executions_TimeScale.CONSIDERATION_SET_EXECUTION_ptr", !dbg !10
  %"num_executions_TimeScale.PASS_ptr" = getelementptr [5 x i32], [5 x i32]* %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 1 , !dbg !10
  %".41" = load i32, i32* %"num_executions_TimeScale.PASS_ptr", !dbg !10
  %".42" = add i32 %".41", 1, !dbg !10
  store i32 %".42", i32* %"num_executions_TimeScale.PASS_ptr", !dbg !10
  %"num_executions_TimeScale.ENVIRONMENT_STATE_UPDATE_ptr" = getelementptr [5 x i32], [5 x i32]* %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 2 , !dbg !10
  %".44" = load i32, i32* %"num_executions_TimeScale.ENVIRONMENT_STATE_UPDATE_ptr", !dbg !10
  %".45" = add i32 %".44", 1, !dbg !10
  store i32 %".45", i32* %"num_executions_TimeScale.ENVIRONMENT_STATE_UPDATE_ptr", !dbg !10
  %"num_executions_TimeScale.ENVIRONMENT_SEQUENCE_ptr" = getelementptr [5 x i32], [5 x i32]* %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 3 , !dbg !10
  %".47" = load i32, i32* %"num_executions_TimeScale.ENVIRONMENT_SEQUENCE_ptr", !dbg !10
  %".48" = add i32 %".47", 1, !dbg !10
  store i32 %".48", i32* %"num_executions_TimeScale.ENVIRONMENT_SEQUENCE_ptr", !dbg !10
  %"num_executions_TimeScale.LIFE_ptr" = getelementptr [5 x i32], [5 x i32]* %"ptr_state_num_executions_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 4 , !dbg !10
  %".50" = load i32, i32* %"num_executions_TimeScale.LIFE_ptr", !dbg !10
  %".51" = add i32 %".50", 1, !dbg !10
  store i32 %".51", i32* %"num_executions_TimeScale.LIFE_ptr", !dbg !10
  %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".5", i32 0, i32 6 , !dbg !10
  %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM" = getelementptr {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}, {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", i32 0, i32 7 , !dbg !10
  %".53" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 0 , !dbg !10
  %".54" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", i32 0, i32 0 , !dbg !10
  %".55" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 0 , !dbg !10
  %".56" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 0 , !dbg !10
  call void @"_OutputPort_INPUT_CIM_CURRENT_CONTEXT_InputPort_0__18"({{}}* %".55", {{}}* %".56", [25 x double]* %".53", [25 x double]* %".54"), !dbg !10
  %".58" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 1 , !dbg !10
  %".59" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", i32 0, i32 1 , !dbg !10
  %".60" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 1 , !dbg !10
  %".61" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 1 , !dbg !10
  call void @"_OutputPort_INPUT_CIM_RETRIEVED_STIMULUS_InputPort_0__20"({{}}* %".60", {{}}* %".61", [8 x double]* %".58", [8 x double]* %".59"), !dbg !10
  %".63" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 2 , !dbg !10
  %".64" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", i32 0, i32 2 , !dbg !10
  %".65" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 2 , !dbg !10
  %".66" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 2 , !dbg !10
  call void @"_OutputPort_INPUT_CIM_CURRENT_TASK_InputPort_0__22"({{}}* %".65", {{}}* %".66", [2 x double]* %".63", [2 x double]* %".64"), !dbg !10
  %".68" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 3 , !dbg !10
  %".69" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", i32 0, i32 3 , !dbg !10
  %".70" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 3 , !dbg !10
  %".71" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 3 , !dbg !10
  call void @"_OutputPort_INPUT_CIM_CURRENT_STIMULUS_InputPort_0__24"({{}}* %".70", {{}}* %".71", [8 x double]* %".68", [8 x double]* %".69"), !dbg !10
  %".73" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 4 , !dbg !10
  %".74" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", i32 0, i32 4 , !dbg !10
  %".75" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 4 , !dbg !10
  %".76" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 4 , !dbg !10
  call void @"_OutputPort_INPUT_CIM_RETRIEVED_CONTEXT_InputPort_0__26"({{}}* %".75", {{}}* %".76", [25 x double]* %".73", [25 x double]* %".74"), !dbg !10
  %".78" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %"ptr_state_value_WORKING MEMORY (fnn) Input_CIM_hist0", i32 0, i32 5 , !dbg !10
  %".79" = getelementptr {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}, {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4", i32 0, i32 5 , !dbg !10
  %".80" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_param_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 5 , !dbg !10
  %".81" = getelementptr {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}* %"ptr_state_output_ports_WORKING MEMORY (fnn) Input_CIM", i32 0, i32 5 , !dbg !10
  call void @"_OutputPort_INPUT_CIM_Target_InputPort_0__28"({{}}* %".80", {{}}* %".81", [2 x double]* %".78", [2 x double]* %".79"), !dbg !10
  %".83" = call i1 @"_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__is_finished_learning_30"({{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".5", {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4"), !dbg !10
  ret i1 %".83", !dbg !10
}

declare void @"_InputPort_INPUT_CIM_CURRENT_CONTEXT_InputPort_0__5"({{double, {}, double, {}}, {}, {}}* %".1", {{}}* %".2", [2 x [25 x double]]* %".3", [25 x double]* %".4") 

declare void @"_InputPort_INPUT_CIM_RETRIEVED_STIMULUS_InputPort_0__7"({{double, {}, double, {}}, {}, {}}* %".1", {{}}* %".2", [2 x [8 x double]]* %".3", [8 x double]* %".4") 

declare void @"_InputPort_INPUT_CIM_CURRENT_TASK_InputPort_0__9"({{double, {}, double, {}}, {}, {}}* %".1", {{}}* %".2", [2 x [2 x double]]* %".3", [2 x double]* %".4") 

declare void @"_InputPort_INPUT_CIM_CURRENT_STIMULUS_InputPort_0__11"({{double, {}, double, {}}, {}, {}}* %".1", {{}}* %".2", [2 x [8 x double]]* %".3", [8 x double]* %".4") 

declare void @"_InputPort_INPUT_CIM_RETRIEVED_CONTEXT_InputPort_0__13"({{double, {}, double, {}}, {}, {}}* %".1", {{}}* %".2", [2 x [25 x double]]* %".3", [25 x double]* %".4") 

declare void @"_InputPort_INPUT_CIM_Target_InputPort_0__15"({{double, {}, double, {}}, {}, {}}* %".1", {{}}* %".2", [1 x [2 x double]]* %".3", [2 x double]* %".4") 

declare void @"_Identity_Identity_Function_0__learning_17"({}* %".1", {}* %".2", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".3", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4") 

declare void @"_OutputPort_INPUT_CIM_CURRENT_CONTEXT_InputPort_0__18"({{}}* %".1", {{}}* %".2", [25 x double]* %".3", [25 x double]* %".4") 

declare void @"_OutputPort_INPUT_CIM_RETRIEVED_STIMULUS_InputPort_0__20"({{}}* %".1", {{}}* %".2", [8 x double]* %".3", [8 x double]* %".4") 

declare void @"_OutputPort_INPUT_CIM_CURRENT_TASK_InputPort_0__22"({{}}* %".1", {{}}* %".2", [2 x double]* %".3", [2 x double]* %".4") 

declare void @"_OutputPort_INPUT_CIM_CURRENT_STIMULUS_InputPort_0__24"({{}}* %".1", {{}}* %".2", [8 x double]* %".3", [8 x double]* %".4") 

declare void @"_OutputPort_INPUT_CIM_RETRIEVED_CONTEXT_InputPort_0__26"({{}}* %".1", {{}}* %".2", [25 x double]* %".3", [25 x double]* %".4") 

declare void @"_OutputPort_INPUT_CIM_Target_InputPort_0__28"({{}}* %".1", {{}}* %".2", [2 x double]* %".3", [2 x double]* %".4") 

declare i1 @"_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__is_finished_learning_30"({{}, {{{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}, {{double, {}, double, {}}, {}, {}}}, double, {}, double, double, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".1", {{}, {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}, [1 x {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}], {}, [1 x double], [1 x [5 x i32]], [1 x double], {{{}}, {{}}, {{}}, {{}}, {{}}, {{}}}}* %".2", {[2 x [25 x double]], [2 x [8 x double]], [2 x [2 x double]], [2 x [8 x double]], [2 x [25 x double]], [1 x [2 x double]]}* %".3", {[25 x double], [8 x double], [2 x double], [8 x double], [25 x double], [2 x double]}* %".4") 

!llvm.module.flags = !{ !0, !1 }
!llvm.dbg.cu = !{ !5, !8 }
!0 = !{ i32 2, !"Dwarf Version", i32 4 }
!1 = !{ i32 2, !"Debug Info Version", i32 3 }
!2 = !DIFile(directory: "/Users/jdc/PyCharmProjects/PsyNeuLink/psyneulink/core/components/mechanisms/processing", filename: "compositioninterfacemechanism.py")
!3 = !{ null }
!4 = !DISubroutineType(types: !3)
!5 = distinct !DICompileUnit(file: !2, isOptimized: false, language: DW_LANG_Python, producer: "PsyNeuLink", runtimeVersion: 0)
!6 = distinct !DISubprogram(file: !2, isLocal: false, line: 0, name: "_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__learning_3", type: !4, unit: !5)
!7 = !DILocation(column: 0, line: 0, scope: !6)
!8 = distinct !DICompileUnit(file: !2, isOptimized: false, language: DW_LANG_Python, producer: "PsyNeuLink", runtimeVersion: 0)
!9 = distinct !DISubprogram(file: !2, isLocal: false, line: 0, name: "_CompositionInterfaceMechanism_WORKING_MEMORY__fnn__Input_CIM__learning_3_internal_4", type: !4, unit: !8)
!10 = !DILocation(column: 0, line: 0, scope: !9)