name: 'Cleanup pip wheels cache'
description: 'Purge pip wheels cache, keeping wheels for the installed packages'

runs:
  using: "composite"
  steps:
   - name: "Cleanup old wheels"
     shell: bash
     run: |
        pip cache info
        INSTALLED=`pip list | sed 's/-/_/g' | sed 's/  */-/' | tail -n+3`
        CACHED=`pip cache list | cut -f 2,3 -d- | tail -n+3`
        for P in $CACHED; do
          # Remove cached and not installed
          if [ `echo $INSTALLED | grep -o $P | wc -l` == "0" ] ; then
            pip cache remove -v $P || true
          fi
        done
