# Princeton University licenses this file to You under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.  You may obtain a copy of the License at:
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.


# ******************************************  WeightedErrorMechanism ***************************************************

"""
Overview
--------

A WeightedErrorMechanism monitors the `outputState <OutputState>` of it's
`errorSource <WeightedErrorMechanism.errorSource>`, a `ProcessingMechanism` that projects to another mechanism in a
`process <Process>` or `system <System>`.  It computes a `weighted_error_signal`, which is the contribution of each
element of the output of the `errorSource <WeightedErrorMechanism.errorSource>` to the error for the output of the
mechanism to which the `errorSource <WeightedErrorMechanism.errorSource>` projects.  The `weighted_error_signal`
returned by the  `function <WeightedErrorMechanism.function>` of the WeightedErrorMechanism is used by a
`LearningProjection` to adjust a `MappingProjection` to the `errorSource <WeightedErrorMechanism.errorSource>`,
so as to reduce its future contribution to the error generated by the network.

.. _WeightedError_Creation:

Creating A WeightedErrorMechanism
---------------------------------

A WeightedErrorMechanism can be created directly by calling its constructor, or using the `mechanism` function and
specifying :keyword:`WeightedErrorMechanism` as its `mech_spec` argument.  It can also be created by
`in context specification of a LearningProjection <Projection_Creation>` for a MappingProjection; that MappingProjection
must project to a ProcessingMechanism that is not a `TERMINAL` mechanism. One or more WeightedErrorMechanisms,
are also `created automatically <LearningProjection_Automatic_Creation>`, along with associated LearningProjections,
when learning is specified for a process or system with any
COMMENT:
    `INTERNAL` [ADD THIS WHEN mechanisms CAN RECEIVE MORE THAN ONE DESIGNATION
COMMENT
ProcessingMechanisms that are not `TERMINAL` or `SINGLETON` mechanisms.

.. _WeightedError_Structure

Structure
---------

A WeightedErrorMechanism has a single `inputState <InputState>` and a single `outputState <OutputState>` (labelled
`WEIGHTED_ERROR`).  It also has four primary attributes:  an

  * `errorSource <WeightedErrorMechanism.errorSource>`: the ProcessingMechanism for which the WeightedErrorMechanism
    computes the `weighted_error_Signal`;
  ..
  * `next_mechanism`: a ProcessingMechanism to which the `errorSource <WeightedErrorMechanism.errorSource>` projects;
  ..
  * `projection_to_next_mechanism`: the `MappingProjection` from the `errorSource <WeightedErrorMechanism.errorSource>`
    to the `next_mechanism`;
  ..
  * `error_signal <WeightedErrorMechanism.error_signal>`: the error for the :keyword:`value` of the `next_mechanism`;
  ..
  * `weighted_error_Signal`: the error for the :keyword:`value` of the `errorSource`, weighted by the contribution that
    each element of its elements makes to the `error_signal <WeightedErrorMechanism.error_signal>`.

The WeightedErrorMechanism receives a MappingProjection to its inputState from the
`errorSource  <WeightedErrorMechanism.errorSource>`, and its `WEIGHTED_ERROR` outputState
is assigned a `LearningProjection` to the MappingProjection it is being used to train (and that projects to the
`errorSource <WeightedErrorMechanism.errorSource>`)

COMMENT:
    Each row of the  `matrix <MappingProjection.MappingProjection.matrix>` for that MappingProjection corresponds to an
    element of the `value` for the `errorSource <WeightedErrorMechanism.errorSource>`, each column corresponds to an
    element of the `value` of the mechanism to which it projects, and each element of the matrix is the weight of the
    association between the two.
COMMENT

.. _WeightedError_Execution

Execution
---------

A WeightedErrorMechanism always executes after the mechanism it is monitoring.  It's
`function <WeightedErrorMechanism.function>` computes its `weighted_error_signal`: the contribution that each element
of the `errorSource <WeightedErrorMechanism.errorSource>` makes to the `error_signal <WeightedErrorMechanism>`
(i.e., the error for the :keyword:`value` of the `next_mechanism`), weighted both by the strength of its association to
each element of the `next_mechanism` (specified in `projection_to_next_mechanism`), and the differential of the
:keyword:`function` of `next_mechanism`.  This implements a core computation of the
`Generalized Delta Rule <http://www.nature.com/nature/journal/v323/n6088/abs/323533a0.html>`_  implemented by the
`BackPropagation` learning function. The `function <WeightedErrorMechanism>` of the WeightedErrorMechanism returns
the `weighted_error_signal`, that is assigned to its `value <WeightedErrorMechanism.value>` and
`outputValue <WeightedErrorMechanism.outputValue>` attributes, and the :keyword:`value` of of its `WEIGHTED_ERROR`
outputState.

.. _WeightedError_Class_Reference:

Class Reference
---------------

"""

# from numpy import sqrt, random, abs, tanh, exp
from PsyNeuLink.Components.Mechanisms.MonitoringMechanisms.MonitoringMechanism import *
# from PsyNeuLink.Components.States.InputState import InputState

# WeightedErrorMechanism output (used to create and name outputStates):
WEIGHTED_ERRORS = 'WeightedErrors'
PROJECTION_TO_NEXT_MECHANISM = 'projection_to_next_mechanism'

# WeightedErrorMechanism output indices (used to index outputValue):
class WeightedErrorOutput(AutoNumber):
    """Indices of the `outputValue <WeightedErrorMechanism.outputValue>` attribute of the WeightedErrorMechanism
    containing the values described below."""
    ERROR_SIGNAL = ()
    """`error_signal` attribute of the WeightedErrorMechanism"""

class WeightedErrorError(Exception):
    def __init__(self, error_value):
        self.error_value = error_value

    def __str__(self):
        return repr(self.error_value)


class WeightedErrorMechanism(MonitoringMechanism_Base):
    """
    WeightedErrorMechanism( \
    error_signal=None,      \
    params=None,            \
    name=None,              \
    prefs=None)

    Implements WeightedErrorMechanism subclass of `MonitoringMechanism <MonitoringMechanism>`.

    COMMENT:
        Description:
            WeightedErrorMechanism is a Subtype of the MonitoringMechanism Type of the Mechanism Category of the
            Component class
            It's function computes the contribution of each sender element (rows of PROJECTION_TO_NEXT_MECHANISM param)
               to the error values of the receivers
                 (elements of the error_signal array, columns of the matrix of the PROJECTION_TO_NEXT_MECHANISM param),
               weighted by the association of each sender with each receiver
               (specified in PROJECTION_TO_NEXT_MECHANISM.matrix)
            The function returns an array with the weighted errors for each sender element

        Class attributes:
            + componentType (str): WeightedErrorMechanism
            + classPreference (PreferenceSet): WeightedError_PreferenceSet, instantiated in __init__()
            + classPreferenceLevel (PreferenceLevel): PreferenceLevel.SUBTYPE
            + variableClassDefault (1D np.array):
            + paramClassDefaults (dict): {PROJECTION_TO_NEXT_MECHANISM: MappingProjection}
            + paramNames (dict): names as above

        Class methods:
            None

        MechanismRegistry:
            All instances of WeightedErrorMechanism are registered in MechanismRegistry, which maintains an
                entry for the subclass, a count for all instances of it, and a dictionary of those instances
    COMMENT


    Arguments
    ---------

    error_signal : 1d np.array
        error for :keyword:`value` of mechanism to which `error_source <WeightedErrorMechanism.error_source>` projects.

    params : Optional[Dict[param keyword, param value]]
        a `parameter dictionary <ParameterState_Specifying_Parameters>` that can be used to specify the parameters
        for the mechanism, its function, and/or a custom function and its parameters. Includes a
        :keyword:`PROJECTION_TO_NEXT_MECHANISM` entry for the `projection_to_next_me.  Values specified
        for parameters in the dictionary override any assigned to those parameters in arguments of the constructor.

    name : str : default WeightedErrorMechanism-<index>
        a string used for the name of the mechanism.
        If not is specified, a default is assigned by `MechanismRegistry`
        (see :doc:`Registry <LINK>` for conventions used in naming, including for default and duplicate names).

    prefs : Optional[PreferenceSet or specification dict : Mechanism.classPreferences]
        the `PreferenceSet` for mechanism.
        If it is not specified, a default is assigned using `classPreferences` defined in __init__.py
        (see :doc:`PreferenceSet <LINK>` for details).

    Attributes
    ----------

    error_source : ProcessingMechanism
        the mechanism for which the WeightedErrorMechanism calculates the error (`weighted_error_signal`);
        sends a `MappingProjection` to the WeightedErrorMechanism.

    next_mechanism : ProcessingMechanism
        a mechanism to which the `error_source <WeightedErrorMechanism.error_source>` projects.

    projection_to_next_mechanism : MappingProjection
        projection from the `errorSource <WeightedErrorMechanism.error_source>` to `next_mechanism`;
        its `matrix <MappingProjection.MappingProjection.matrix>` parameter is used to calculate the
        `weighted_error_signal`.

    error_signal : 1d np.array
        error for the :keyword:`value` of `next_mechanism`.

    variable : 1d np.array
        same as `error_signal <WeightedErrorMechanism.error_signal>`; used by
        `function <WeightedErrorMechanism.function>` to compute `weighted_error_signal
        <WeightedErrorMechanism.weighted_error_signal>`.

    weighted_error_signal : 1d np.array
        the contribution made by each element of the `value` of the `error_source
        <WeightedErrorMechanism.error_source>` to the :keyword:`error_signal` for `next_mechanism`.

    value : 1d np.array
        result of `function <WeightedErrorMechanism.function>`, same as `weighted_error_signal`.

    outputValue : List[1d np.array]
        list with single item that is the same as `weighted_error_signal` and `value <WeightedErrorMechanism.value>`.

    name : str : default WeightedErrorMechanism-<index>
        the name of the mechanism.
        Specified in the `name` argument of the constructor for the projection;
        if not is specified, a default is assigned by `MechanismRegistry`
        (see :doc:`Registry <LINK>` for conventions used in naming, including for default and duplicate names).

    prefs : PreferenceSet or specification dict : Mechanism.classPreferences
        the `PreferenceSet` for mechanism.
        Specified in the `prefs` argument of the constructor for the mechanism;
        if it is not specified, a default is assigned using `classPreferences` defined in __init__.py
        (see :doc:`PreferenceSet <LINK>` for details).


    """

    componentType = WEIGHTED_ERROR_MECHANISM

    classPreferenceLevel = PreferenceLevel.SUBTYPE
    # These will override those specified in TypeDefaultPreferences
    classPreferences = {
        kwPreferenceSetName: 'WeightedErrorCustomClassPreferences',
        kpReportOutputPref: PreferenceEntry(False, PreferenceLevel.INSTANCE)}

    variableClassDefault = [0]  # error_signal

    # WeightedErrorMechanism parameter assignments):
    paramClassDefaults = Mechanism_Base.paramClassDefaults.copy()
    paramClassDefaults.update({
        PROJECTION_TO_NEXT_MECHANISM: None,
        OUTPUT_STATES:[WEIGHTED_ERRORS],
    })

    paramNames = paramClassDefaults.keys()

    @tc.typecheck
    def __init__(self,
                 error_signal=None,
                 params=None,
                 name=None,
                 prefs:is_pref_set=None,
                 context=None):
        """Assign type-level preferences and call super.__init__
        """

        self.function = self.execute

# # FIX: MODIFY get_param_value_for_keyword TO TAKE PARAMS DICT

        # Assign args to params and functionParams dicts (kwConstants must == arg names)
        params = self._assign_args_to_param_dicts(params=params)

        super().__init__(variable=error_signal,
                         params=params,
                         name=name,
                         prefs=prefs,
                         context=self)

    def _validate_params(self, request_set, target_set=None, context=None):
        """Insure that width of PROJECTION_TO_NEXT_MECHANISM matrix equals length of error_signal

        Validate that width of matrix for projection in PROJECTION_TO_NEXT_MECHANISM param equals length of error_signal
        """

        super()._validate_params(request_set=request_set, target_set=target_set, context=context)
        cols = target_set[PROJECTION_TO_NEXT_MECHANISM].matrix.shape[1]
        error_signal_len = len(self.variable[0])
        if  cols != error_signal_len:
            raise WeightedErrorError("Number of columns ({}) of weight matrix for {}"
                                     " must equal length of error_signal ({})".
                                     format(cols,self.name,error_signal_len))

    def _instantiate_attributes_before_function(self, context=None):
        self.next_mechanism = self.paramsCurrent[PROJECTION_TO_NEXT_MECHANISM].receiver.owner
        super()._instantiate_attributes_before_function(context=context)

    def _execute(self,
                variable=None,
                runtime_params=None,
                clock=CentralClock,
                time_scale = TimeScale.TRIAL,
                context=None):

        """Compute weighted_error_signal for errorSource from derivative of error_signal for mechanism it projects to.

        Return weighted_error_signal.
        """

        if not context:
            context = EXECUTING + self.name

        self._check_args(variable=variable, params=runtime_params, context=context)

        # Get error signal from monitoring mechanism for next mechanism in the process
        error = self.variable[0]

        # Get weight matrix for projection from next mechanism in the process (to one after that)
        next_level_matrix = self.paramsCurrent[PROJECTION_TO_NEXT_MECHANISM].matrix

        # Get output of the next mechanism in the process
        next_level_output = self.next_mechanism.outputState.value

        # Get derivative for next mechanism's function
        derivative_fct = self.next_mechanism.function_object.derivative


        # Compute derivative of error with respect to current output of next mechanism
        output_derivative = derivative_fct(output=next_level_output)
        error_derivative = error * output_derivative

        # Compute error terms for each unit of current mechanism weighted by contribution to error in the next one
        self.weighted_error_signal = np.dot(next_level_matrix, error_derivative)

        # Compute summed error for use by callers to decide whether to update
        self.summed_error_signal = np.sum(self.weighted_error_signal)

        return self.weighted_error_signal

