"""Opt-in batched simulation support for stochastic PsyNeuLink compositions."""

from psyneulink.core.batched.compiler import (
    BatchedCompileError,
    BatchedCompositionCompiler,
    BatchedSimulationPlan,
)
from psyneulink.core.batched.specs import (
    BatchedOpSpecError,
    DenseProjectionSpec,
    ElementwiseFunctionSpec,
    MechanismOpSpec,
    OutputDecl,
    ParamBinding,
    PassthroughMechanismSpec,
    RngDecl,
    StateDecl,
    batched_node_op,
    batched_op,
    param,
    register_batched_instance_op,
    register_batched_op,
    unregister_batched_instance_op,
)
from psyneulink.core.batched.diagnostics import (
    BatchedCapabilityReport,
    BatchedDiagnostic,
)
from psyneulink.core.batched.likelihood import (
    histogram_likelihood,
    histogram_log_likelihood,
)
from psyneulink.core.batched.ir import (
    BatchedCompositionIR,
    BatchedGraphIR,
    BatchedInputSpec,
    BatchedNodeSpec,
    BatchedOp,
    BatchedOutputSpec,
    BatchedParamSpec,
    BatchedProjectionSpec,
    BatchedSchedulerSpec,
    BatchedSimulationResult,
    BatchedStateSpec,
)

__all__ = [
    "BatchedCapabilityReport",
    "BatchedCompileError",
    "BatchedCompositionCompiler",
    "BatchedCompositionIR",
    "BatchedDiagnostic",
    "BatchedGraphIR",
    "BatchedInputSpec",
    "BatchedNodeSpec",
    "BatchedOp",
    "BatchedOpSpecError",
    "BatchedOutputSpec",
    "BatchedParamSpec",
    "BatchedProjectionSpec",
    "BatchedSchedulerSpec",
    "BatchedSimulationPlan",
    "BatchedSimulationResult",
    "BatchedStateSpec",
    "DenseProjectionSpec",
    "ElementwiseFunctionSpec",
    "MechanismOpSpec",
    "OutputDecl",
    "ParamBinding",
    "PassthroughMechanismSpec",
    "RngDecl",
    "StateDecl",
    "batched_node_op",
    "batched_op",
    "histogram_likelihood",
    "histogram_log_likelihood",
    "param",
    "register_batched_instance_op",
    "register_batched_op",
    "unregister_batched_instance_op",
]
